apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - cluster_role.yaml
  - cluster_role_binding.yaml
  - jaegertracing.io_jaegers_crd.yaml
  - operator.yaml
  - service_account.yaml
  - namespace.yaml
  - instance.yaml
